export const REPO_NAME_SYMBOL = "$REPO_NAME";
export const REPO_URL_SYMBOL = "$REPO_URL";
export const NO_COMMITS_SYMBOL = "$NO_COMMITS";
export const COMMITS_URL_SYMBOL = "$COMMITS_URL";
export const PRIMARY_LANGUAGE_SYMBOL = "$PRIMARY_LANGUAGE";
export const REPO_DESCRIPTION_SYMBOL = "$REPO_DESCRIPTION";
export const HEADER_SYMBOL = "$HEADER";
export const DEFAULT_HEADER_FORMAT = `[${REPO_NAME_SYMBOL}](${REPO_URL_SYMBOL}) \
- [${NO_COMMITS_SYMBOL}](${COMMITS_URL_SYMBOL}) - ${PRIMARY_LANGUAGE_SYMBOL}\n${REPO_DESCRIPTION_SYMBOL}`;
export const DEFAULT_HIGHLIGHT_FORMAT = `⭐ ${HEADER_SYMBOL}`;
